gpu: fix cl compilation on amd gpus
error: call to 'mix' is ambiguous
    float h1 = mix(tile_height(tileHeightImage, plane, sx, sz), tile_height(tileHeightImage, plane, sx + 1, sz), fract(fx, &it));
(cherry picked from commit 7935a7615ce3fc6aa668e78416997e3fec88223f)